### ISSUE TITLE
Create UI design

### ISSUE THREAD

**Issue by rajivharlalka** [rajivharlalka/Accio#20]
UI design for the theme needs to be made

**Comment by simar1931021** [comment]
Hey @rajivharlalka can I come up with some designs??

**Comment by mdsimar1901** [comment]
Hey @rajivharlalka can I come up with some designs?

**Comment by rajivharlalka** [comment]
Sure you can go ahead

**Comment by mdsimar1901** [comment]
is there any specifiacations??
Also does it need to be responsice//

**Comment by rajivharlalka** [comment]
As such there isn't any specification . Sticking to the same color scheme would be appreciated . Designing of how different components ( eg : Post page can have a contents templated to show the heading in the particular md file) can look is what's needed most.
