### ISSUE TITLE
Logo for the theme

### ISSUE THREAD

**Issue by rajivharlalka** [rajivharlalka/Accio#21]
The theme would require a logo

**Comment by chirag828049** [comment]
It will be great if the literal meaning of the word "Accio" is used while making the logo

**Comment by aryanploxxx** [comment]
I would like to work on this project 🙂

**Comment by rajivharlalka** [comment]
Sure, Assigning it to you, @chirag828049 would be more helpful in case of queries to this issue... 

A simple logo must be enough , try to stick to SVG format for the logo and you may add the logo in the static directory present in the root.

**Comment by chirag828049** [comment]
#39
