### ISSUE TITLE
Styling lists

### ISSUE THREAD

**Issue by rajivharlalka** [rajivharlalka/Accio#22]
Currently the list are not getting styled properly
![image](https://user-images.githubusercontent.com/68731551/143767789-4b2d017d-b0cb-4fba-9dc7-3a159f673f47.png)

This needs to made nice in a format which looks nice

**Comment by rajivharlalka** [comment]
![image](https://user-images.githubusercontent.com/68731551/144569041-4a47161d-7b7b-40af-837b-6a5a99a7047d.png)

 desciption , tags and date of post present in frontmatter should also be visible in the list of posts

**Comment by NotRohanPaul** [comment]
Can I work on this issue?

**Comment by rajivharlalka** [comment]
Sure @NotRohanPaul , assigning it to you. You may ping any one of the maintainer(myself or @chirag828049 ) in case of any issue, think of some minimilist design. For the implementation you can refer to the reference blog themes given in the readme.

**Comment by NotRohanPaul** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/75577230/144587549-75d55057-7ba2-4e21-869b-53cd57be7027.png)

**Comment by rajivharlalka** [comment]
For now, it looks good to some extent. Some suggestions 
- Maybe you can remove the bullet points
- The font weight of the heading can be increased as well as the font size can be decreased by a bit.
- Space between two posts is appearing to be very large, that can be seen later though

Any other suggestion from your side @chirag828049 ?

**Comment by NotRohanPaul** [comment]
Let me experiment with different changes and see which looks better.

**Comment by rajivharlalka** [comment]
Sure, you can test whatever you feel like 😄

**Comment by chirag828049** [comment]
Looks neat. I like it.

If you need suggestions,
1. The space between posts is fine. 
2. Yeah I guess we can remove the bullet points. Can try adding some arrow icon to make it look better.
3. Is that subtext required ?

**Comment by NotRohanPaul** [comment]
ok

**Comment by NotRohanPaul** [comment]
![Capture2](https://user-images.githubusercontent.com/75577230/144635772-bdbd9d9b-1624-492c-829e-8dfec0109749.PNG)
How it looks?

**Comment by NotRohanPaul** [comment]
used icon is from font awesome

**Comment by chirag828049** [comment]
Closing this.
