### ISSUE TITLE
Styling different Markdown Components

### ISSUE THREAD

**Issue by rajivharlalka** [rajivharlalka/Accio#23]
Different Markdown components can be styled differently which may look nice.
![image](https://user-images.githubusercontent.com/68731551/143767845-a440d216-5169-4cd5-b627-b708892ccd51.png)
^ Components like blockquote can be styled nicely

**Comment by sidkhuntia** [comment]
![Screen Shot 2021-12-06 at 10 31 11](https://user-images.githubusercontent.com/77291662/144789989-095bfd9b-3c53-44e6-b6be-ce7fdeda5c1f.png)

## Bug
![Screen Shot 2021-12-06 at 10 33 13](https://user-images.githubusercontent.com/77291662/144790202-38d425c9-33f8-42a5-926e-ca9ebbd554f2.png)

## Solution
![Screen Shot 2021-12-06 at 10 32 40](https://user-images.githubusercontent.com/77291662/144790220-9ef1842c-77ca-4b0a-95cd-153dc89ab82a.png)


I have tried something with the code part only and fixed a minor bug.
I have one doubt what more can be done ?

**Comment by rajivharlalka** [comment]
Actuall this issue was made to fix styling of all markdown components like codeblocks , italics , quotes etc

**Comment by sidkhuntia** [comment]
yes i will  try those also. I just wanted to ask is the code syntax part good enough ?

**Comment by rajivharlalka** [comment]
Actually didnt get what you try to share, could you please share a complete screenshot.
