### ISSUE TITLE
Categories Taxonomy needs Correction

### ISSUE THREAD

**Issue by rajivharlalka** [rajivharlalka/Accio#24]
![image](https://user-images.githubusercontent.com/68731551/143767900-da02b88b-5572-4abf-93ea-cc65c98d928b.png)

This doesnt look good at all. Styling ideas are invited so that this may look good

Some reference
![image](https://user-images.githubusercontent.com/68731551/143768078-28f126ec-8e0f-40f5-a824-979c9a9dffd7.png)

**Comment by sidkhuntia** [comment]
I would like to work on it
