### ISSUE TITLE
Resume should be opened in new tab

### ISSUE THREAD

**Issue by NotRohanPaul** [rajivharlalka/Accio#25]

**Comment by NotRohanPaul** [comment]
While clicking the Resume in the Navigation bar the Resume file should open in new tab

**Comment by rajivharlalka** [comment]
Would You like to work on this issue yourself?

**Comment by NotRohanPaul** [comment]
Yes

**Comment by rajivharlalka** [comment]
Assigning it you then.

**Comment by NotRohanPaul** [comment]
![Capture](https://user-images.githubusercontent.com/75577230/144607513-e339b884-e953-42bc-a024-2efa5470f2be.PNG)

**Comment by chirag828049** [comment]
Closing this.
