### ISSUE TITLE
Shift Post to home Page

### ISSUE THREAD

**Issue by rajivharlalka** [rajivharlalka/Accio#30]
Since this would be a blog page and not a portfolio page , it would be better to have the posts enlisted in the home page just after the introduction , instead of having a dedicated tab on navbar. 

@chirag828049  what's your say?

**Comment by chirag828049** [comment]
We can go with latest 3-4 blogs in homepage. Posts page will have all posts. How about this ?

**Comment by rajivharlalka** [comment]
Why have a posts page, pagination can be done from the home page itself, or you wanna make something like most recent posts

**Comment by chirag828049** [comment]
yeah
