### ISSUE TITLE
Change the looks of "About me" page

### ISSUE THREAD

**Issue by NotRohanPaul** [rajivharlalka/Accio#40]

**Comment by NotRohanPaul** [comment]
I am starting to work on it.

**Comment by rajivharlalka** [comment]
Sure, go ahead

**Comment by NotRohanPaul** [comment]
![About me v1](https://user-images.githubusercontent.com/75577230/147385326-77463da3-002d-4f04-88bf-96c3d46d0948.PNG)
Added some letter spacing also the wave emoji is animated.

**Comment by NotRohanPaul** [comment]
can I make a pull request

**Comment by rajivharlalka** [comment]
@chirag828049

**Comment by chirag828049** [comment]
Umm everything good. Though I don't think we should change the letter spacing.

**Comment by NotRohanPaul** [comment]
ok

**Comment by NotRohanPaul** [comment]
![About me v2](https://user-images.githubusercontent.com/75577230/147483955-2c405bf3-8fef-4195-b5ee-67f916fcfe7f.PNG)
How it is now?

**Comment by NotRohanPaul** [comment]
@rajivharlalka @chirag828049 Anything else to modify ?

**Comment by chirag828049** [comment]
I like it. How's the mobile view though ?

**Comment by NotRohanPaul** [comment]
![About me v4](https://user-images.githubusercontent.com/75577230/147495261-5128f545-4ab2-4691-bd87-4c02329f4e9f.PNG)
Is the font size correct?

**Comment by chirag828049** [comment]
cool. good work.
Merging.

**Comment by NotRohanPaul** [comment]
can i give a pull request?

**Comment by NotRohanPaul** [comment]
ok
